### ISSUE TITLE
讲讲啥思路啊

### ISSUE THREAD

**Issue by zhiyou007** [Exrick/xpay#1]
讲讲啥思路啊

**Comment by Exrick** [comment]
@zhiyou007 请查看源码

**Comment by ysuhy** [comment]
代码都给你了 ， 你还要思路

**Comment by shoaly** [comment]
@zhiyou007  其实就是先预设自己的收款码, 有定额的收款码, 也有自定义金额的. 然后他的作用就是让客户在扫码之前, 先填写邮箱, 手机号等备注信息. 
这样在收款方看来, 应该是先收到支付到帐的推送(银行, 微信, 支付宝发送的), 然后再去对应的订单记录里面根据金额和时间核对 付款人信息, 并手动标记 每一笔支付是否真的到帐... 

但是其实做到这一步了, 不如在自己网站里面贴上自定义金额的收款吗, 然后跟客户讲清楚, 请在备注里面填写好订单商品信息即可...

**Comment by Sabirjan** [comment]
我还以为抓包微信支付宝的支付订单列表，然后自动检验呢...

**Comment by whp1473** [comment]
抓支付宝和微信的支付订单列表风险很高吧，爬虫检查风险高会封号的。

**Comment by taruling** [comment]
> @zhiyou007 其实就是先预设自己的收款码, 有定额的收款码, 也有自定义金额的. 然后他的作用就是让客户在扫码之前, 先填写邮箱, 手机号等备注信息.
> 这样在收款方看来, 应该是先收到支付到帐的推送(银行, 微信, 支付宝发送的), 然后再去对应的订单记录里面根据金额和时间核对 付款人信息, 并手动标记 每一笔支付是否真的到帐...
> 
> 但是其实做到这一步了, 不如在自己网站里面贴上自定义金额的收款吗, 然后跟客户讲清楚, 请在备注里面填写好订单商品信息即可...

那这手动核对 - - 不靠这个也可以啊 -- 还以为可以自动核对
那就没啥意义可言了。

**Comment by xivcm** [comment]
看了半天。。终于懂了

**Comment by Enbuly** [comment]
人工审核。。。

**Comment by totzcc** [comment]
> @zhiyou007 其实就是先预设自己的收款码, 有定额的收款码, 也有自定义金额的. 然后他的作用就是让客户在扫码之前, 先填写邮箱, 手机号等备注信息.
> 这样在收款方看来, 应该是先收到支付到帐的推送(银行, 微信, 支付宝发送的), 然后再去对应的订单记录里面根据金额和时间核对 付款人信息, 并手动标记 每一笔支付是否真的到帐...
> 
> 但是其实做到这一步了, 不如在自己网站里面贴上自定义金额的收款吗, 然后跟客户讲清楚, 请在备注里面填写好订单商品信息即可...

"人工" 智能审核

**Comment by netstu** [comment]
这样有什么意思啊

**Comment by ZhouHoubin** [comment]
比如支付宝的,打开支付宝二维码扫码,得到地址 alipays://platformapi/startapp?appId=20000067&url=http://xpay.exrick.cn/openAlipay?money=5.00&num=0228&id=460f0fda-a3d7-4073-9d26-7b3ffc80fc09,支付宝会自动跳转到url 地址,这个地址会调用支付宝的js api 跳转到转账收款页面,中间加了一层就是方便做订单管理吧,看了好久才发现是人工审核的

**Comment by Exrick** [comment]
@ZhouHoubin 主要是为了让大家体验其他方式  ![IMG_3118.PNG](https://i.loli.net/2019/03/18/5c8f0f5c9c11b.png)

**Comment by ZhouHoubin** [comment]
> 果然不敢放大招， 监听做不了，就不要发，
> 这种方案没什么用处


监听无非通知栏监听，模块监听，找找就有了
