### ISSUE TITLE
说了这么多这还是人工审核的？

### ISSUE THREAD

**Issue by tetsaicn** [Exrick/xpay#17]
这套系统存在的目的就是发个邮件通知下管理就没了？那这有个卵用啊，浪费我1块钱

**Comment by tetsaicn** [comment]
闲的蛋疼，也不在首页说说是【人工】的，浪费时间

**Comment by tetsaicn** [comment]
垃圾东西 👎👎

**Comment by kyriej** [comment]
这么垃圾的吗

**Comment by deepdream88** [comment]
还行，这也是一种方案，只是我个人觉得，目前除了作者自己的商城，并没有其他商城系统支持xpay，这就是我放弃xpay的原因。
