### ISSUE TITLE
无意路过此地，没想到原来是类似思路额

### ISSUE THREAD

**Issue by yunluo** [Exrick/xpay#18]
。。。
以前做过类似的功能
WordPress积分充值
充值后发邮件
一个是同意链接
一个是驳回链接
。。。。

**Comment by Tai7sy** [comment]
日交易几千单是不是要雇人查账点邮件。。。。

**Comment by caozongchao** [comment]
> 日交易几千单是不是要雇人查账点邮件。。。。

赚的钱还不够给客服的钱。。。

**Comment by huangjianguohjg** [comment]
没啥卵用
