### ISSUE TITLE
测试支付不行了，支付宝打开没反应了！！！

### ISSUE THREAD

**Issue by ajiansoft** [Exrick/xpay#22]
alipays://platformapi/startapp?appId=09999988&actionType=toAccount&goBack=NO&userId=2088012242122163&amount=66.66&memo=测试
这个能呼出支付宝，但是只停留在支付宝首页，付款界面呢？

**Comment by hexiaoleione** [comment]
有没有新的解决方案？

**Comment by Exrick** [comment]
近期尝试使用Alipay JSSDK解决

**Comment by ajiansoft** [comment]
研究了一下，期待解决！

**Comment by moneytt** [comment]
期待解决

**Comment by Exrick** [comment]
期末备考 1.8号后更新

**Comment by Exrick** [comment]
最新v1.7版本已修复发布 官网测试获取 @ajiansoft @hexiaoleione @moneytt

**Comment by xiaorongbin** [comment]
新版本苹果测试没问题，但是安卓手机还是无法正常使用

**Comment by Exrick** [comment]
支付宝已禁止alipays://外部链接访问
