### ISSUE TITLE
思路是故意不写清楚的吗

### ISSUE THREAD

**Issue by longhengyu** [Exrick/xpay#29]
Readme 把其它的流程总结一番（言语中还带有鄙视之意），但没有对自己的流程作细致的描述，仔细看下来，需要“人工审核”确实有脱裤放屁之感，完全没有解决个人收款中的痛点。

建议把 Readme 好好写写，不要浪费大家的时间和期待。谢谢。

**Comment by Exrick** [comment]
流程图文很清楚了 demo也可以填体验管理员审核邮箱 如果你是正真个人用量少的收款 你会发现还是人工审核方案好

**Comment by hlevel** [comment]
人工审核方案 我想问晚上怎么弄？不会一天24小时盯着把。。

**Comment by Exrick** [comment]
系统有定时自动关闭支付的...

**Comment by hlevel** [comment]
晚上关闭掉业务睡觉，可以！怎么这么优秀! 这个解决方案很棒！

**Comment by longhengyu** [comment]
> 人工审核方案 我想问晚上怎么弄？不会一天24小时盯着把。。
@hlevel 
所以该项目没有解决任何关键问题，如果是人工处理的话，在微信里也看到收款信息。
该程序只解决了一个痒点，就是处理收款时可以简化一下流程，点一个自动发货按钮什么的。。。
但这始终是痒点，个人支付痛点在于无人执守时的任务处理。这个问题没有解决，加上前面一堆带鄙视的评价别人方案的文字介绍，显得太抬高自己了。别人的方案虽然也不完美，但毕竟都是在解决真正的痛点。

**Comment by hlevel** [comment]
实现思路也很简单，没啥故意不写清楚的，该方案也说清楚了，根据自己的业务选择，不合适自己就不要要求太高了，自动值守也有很多方案的。选择自己合适的才是关键.

**Comment by hlevel** [comment]
建议作者也把自己的描述改下，有点 恐慌嫌疑，来提高自己的方案是独一无二选择, 作者自己也知道自己方案只适合有人值守的业务.

**Comment by Exrick** [comment]
已修改 还有不当的地方麻烦再提一下

**Comment by zheng03** [comment]
其实这个方案确实脱裤子放屁，但作者把页面做的比较好点，让人感觉高端了

**Comment by zoraringsane** [comment]
> 其实这个方案确实脱裤子放屁，但作者把页面做的比较好点，让人感觉高端了

还有买的star和follower 笑死
