### ISSUE TITLE
如何检测订单在支付宝和微信已支付

### ISSUE THREAD

**Issue by froyot** [Exrick/xpay#3]
代码的逻辑只是用户点击了支付之后，发邮件给管理员，管理员收到邮件之后验证订单。所以如何快速有效的验证订单也是非常重要，人工没办法保证24小时时时在线

**Comment by skiy** [comment]
是人工校验支付成功状态的？

**Comment by Exrick** [comment]
@froyot 1.限制交易时间 2.让用户添加支付备注订单标识验证
