### ISSUE TITLE
无语，这纯粹就是靠人工核对，没什么用处的玩意，没点干货就别乱吹！

### ISSUE THREAD

**Issue by QueryStyle** [Exrick/xpay#33]
没点干货就别吹，实在想不到这么奇葩无用的办法居然还有人支持？
这纯粹就是预备好各类收款码，然后在支付页面供用户选择其中一种，用户提交后展示收款码的同时将用户提交的信息发到指定邮箱，然后由人工去核对那段时间里有没有人付款，以此来确定是通过审核还是驳回。
这操作真是溜，自己玩玩也就算了，发出来踩其他种类的实现，不知道你哪来的脸？

口气冲了点，主要因为这操作实在恶心了点，因为目前我自己就用Flutter写了个APP，依靠监听通知栏里支付宝和微信的支付通知信息实现7*24自动核对APP用户的充值信息，主要还是因为要挂台手机做监听觉得实现不够好，想看看网上还有没有其他更好的方案，网上找了一圈发现各种方案都差不多。然而最后发现就你这个最能吹，仔细一看才发现你这个只适合吹不适合用。

最后：最垃圾的方案，没有之一，这年头还想着纯人工审核操作，你真不配当个程序员。

头一次在gayhub上骂人，记录下！

**Comment by unclemcz** [comment]
> 没点干货就别吹，实在想不到这么奇葩无用的办法居然还有人支持？
> 这纯粹就是预备好各类收款码，然后在支付页面供用户选择其中一种，用户提交后展示收款码的同时将用户提交的信息发到指定邮箱，然后由人工去核对那段时间里有没有人付款，以此来确定是通过审核还是驳回。
> 这操作真是溜，自己玩玩也就算了，发出来踩其他种类的实现，不知道你哪来的脸？
> 
> 口气冲了点，主要因为这操作实在恶心了点，因为目前我自己就用Flutter写了个APP，依靠监听通知栏里支付宝和微信的支付通知信息实现7*24自动核对APP用户的充值信息，主要还是因为要挂台手机做监听觉得实现不够好，想看看网上还有没有其他更好的方案，网上找了一圈发现各种方案都差不多。然而最后发现就你这个最能吹，仔细一看才发现你这个只适合吹不适合用。
> 
> 最后：最垃圾的方案，没有之一，这年头还想着纯人工审核操作，你真不配当个程序员。
> 
> 头一次在gayhub上骂人，记录下！

实现方式各有优劣，只是说这种不适合你吧，另外你的需求可以考虑下payjs.cn，很人性化的个人支付通道。

**Comment by zjh4473** [comment]
我觉得楼主说的很对。这种确实没什么叼用。。。。

**Comment by lzx8589561** [comment]
可以二开呀，收到支付成功进行回调也可以呀。没有这么差劲吧
