### ISSUE TITLE
错误: 找不到或无法加载主类 cn.exrick.XpayApplication

### ISSUE THREAD

**Issue by JankingWon** [Exrick/xpay#35]
用IDEA直接打开项目报错怎么破

**Comment by JankingWon** [comment]
[ERROR] Failed to execute goal on project xpay: Could not resolve dependencies for project cn.exrick:xpay:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.springframework.boot:spring-boot-starter:jar:1.5.9.RELEASE, org.spring
framework.boot:spring-boot:jar:1.5.9.RELEASE, org.springframework.boot:spring-boot-starter-logging:jar:1.5.9.RELEASE, org.springframework:spring-aop:jar:4.3.13.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-starter:jar
:1.5.9.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.40.215] failed: Connection timed out: connect -> [Help 1]

**Comment by Exrick** [comment]
Maven安装没 依赖包安装下

**Comment by Exrick** [comment]
更新源码试试
