### ISSUE TITLE
扫描收款码之后如何直接拉起立即付款弹框，而不用先点击一次确认付款按钮？

### ISSUE THREAD

**Issue by farwish** [Exrick/xpay#40]
扫描收款码，展示的是 "个人头像+金额+确认付款按钮" 的内容，需要点击内容里的 "确认付款" 按钮之后才能拉起 "立即付款" 的半屏支付弹窗，如何做到扫描二维码直接拉起支付弹窗？@Exrick

**Comment by Exrick** [comment]
使用当面付 @farwish

**Comment by farwish** [comment]
xpay网站使用到的当面付在哪里可以找到具体介绍，是固定金额的吗，或者说链接参数是什么样的 (alipays://platformapi.xxxxx) ?
![image](https://user-images.githubusercontent.com/6552412/59602907-8eb70300-913a-11e9-842a-9d1671240295.png)
@Exrick
