### ISSUE TITLE
xpay的原理是人工审核，不能自动通知。望希望以此做收款的朋友了解清楚。

### ISSUE THREAD

**Issue by winimi** [Exrick/xpay#47]
建议作者将原理说清楚，**人工确认收款**！ 完全无法商用，否则有虚假和诈骗嫌疑。

同时与其它方案对比可以去掉，不要否定其他人的方案抬高自己。

其它方案都是自动监控，不论其它方案好坏与否，与其它方案都不是一个东西。

本人捐赠二次，第一次时间较早，一段时间后忘了看代码。此次捐赠，本意用来维护一套系统充值。看代码后有种感觉智商受到了侮辱，感觉上当受骗。7个支付通道，人工核对订单细节无异于回到原始社区。

如下为官方文档中描述原理：（模棱二可，第2条）

“
1. 用户下单将发送一封审核邮件至你配置的邮箱
2. 若收到支付宝或微信到账通知 再根据邮件中的信息核对 点击通过链接执行你代码中的回调方法 
接入你自己的业务请修改回调方法或链接即可
其它订单邮件不用管 已写好定时任务自动自动处理删除
3. 标识号说明 同1张金额可添加不同备注标识来区分 自定义二维码系统将随机生成4位数让用户填写至付款备注中
”

最后将xpay原理简单附上：

用户下单发邮件到你邮箱
人工看哪个通道有充值（备注信息）
人工去邮箱中找相应的邮件，点击链接

可以归结于无任何意义，如以此方案，可使用更简单方案

人工看哪个通道有充值（备注信息）
人工业务后台充值

**Comment by winimi** [comment]
另外本人严重怀疑demo中作者自己使用的是自动监控，而没将此部分开源。有可能就是app监听

**Comment by Exrick** [comment]
Readme和官网流程写的很清楚了 麻烦仔细阅读 github上也提交了文档文件夹 包含你贴出的内容
【前两个官方通道是 **自！动！回！调！** 的，麻烦看下文档！】

**Comment by deepdream88** [comment]
是啊，我第一次看也有点懵。我比较质疑作者人品

**Comment by zheng03** [comment]
人工审核的....

**Comment by sunyajie0829** [comment]
我是真的不想说难听的话,但是项目描述确实写的不够清楚,简单说就是 XPay 需要自己审核,然后自己核对是谁的付款,然后自己去进行发货/类似操作.另外,这里说的"自!动!回!调!",这个明明就是官方的回调啊,自己配置好了回调以后,官方的逻辑就是这样的,跟你这 XPay 有什么关系么?正常的商户流程肯定是官方回调啊.Github 里面不应该有这种项目存在,或者不应该有这种描述不明且收费的项目存在!

**Comment by Nobellcq** [comment]
这个库的原理看了好几次终于明白了。。。。。
只能说要么作者表达存在严重问题。。
要么作者故意的。。
