### ISSUE TITLE
PayServiceImpl.java中payDao.findOne(id)和 payDao.delete(id)兩個報錯！

### ISSUE THREAD

**Issue by RussiaVk** [Exrick/xpay#49]
![image](https://user-images.githubusercontent.com/43515485/69508907-2df5e700-0f72-11ea-9b8e-7652d95bf03e.png)
![image](https://user-images.githubusercontent.com/43515485/69508916-351cf500-0f72-11ea-9cbf-552258e9a6da.png)

**Comment by Exrick** [comment]
这是jpa封装的方法怎么会报错呢 请确保maven依赖包安装完毕
