### ISSUE TITLE
代码有木马病毒啊---\xpay-code\src\main\resources\static\assets\js\vendor\bootstrap.min.js [Win32.Trojan.Agent.Auto]  [删除成功]

### ISSUE THREAD

**Issue by xzants** [Exrick/xpay#53]
![image](https://user-images.githubusercontent.com/28720306/79933868-bf1aac80-8483-11ea-8ff3-5252d1c16b5c.png)

**Comment by Exrick** [comment]
1.可能是拷贝别处的js导致的
2.可能是误报
3.代码里好像用的cdn，没有用到该文件，建议线上也使用cdn链接
