### ISSUE TITLE
XPay只能进行人工审核!只能进行人工审核!只能进行人工审核!

### ISSUE THREAD

**Issue by sunyajie0829** [Exrick/xpay#64]
我是真的不想说难听的话,但是项目描述确实写的不够清楚,或者说思路不够清晰?
简单说就是 XPay 需要自己审核,然后自己核对是谁的付款,然后自己去进行发货/类似操作.
另外,这里说的"自!动!回!调!",这个明明就是官方的回调啊,自己配置好了回调以后,官方的逻辑就是这样的,跟你这 XPay 有什么关系么?正常的商户流程肯定是官方回调啊.Github 里面不应该有这种项目存在,或者不应该有这种描述不明且收费的项目存在!

**Comment by Exrick** [comment]
readme哪里没写清楚欢迎指出

**Comment by wexiuwexiu** [comment]
有毒
