### ISSUE TITLE
我靠，demo里的扫码领红包，我领导了 22块

### ISSUE THREAD

**Issue by bestK** [Exrick/xpay#7]
![image](https://user-images.githubusercontent.com/14979305/42612420-dee18a68-85cd-11e8-988c-0b70bc1e6d7f.png)

**Comment by chanjamin** [comment]
Niubi,这也要晒出来

**Comment by bestK** [comment]
@chanjamin :sunglasses:

**Comment by w4-hanggi** [comment]
这是消费红包
