### ISSUE TITLE
误导性的项目，根本不是自动判断成功收款，需要人工check

### ISSUE THREAD

**Issue by iuhnayoug** [Exrick/xpay#70]
这个东西浪费我一天的时间去搞懂他到底是啥。他对比的那些软件都是自动进行回调check用户是否支付成功，而这个项目就是在前端发个邮件给后台告诉你说谁通过啥付了款，你去人工check收款成功没，这有什么用？？？？这是你所谓的自动回调么？不如我天天24小时看着手机check到账没，难怪你默认1点-8点关闭系统的。我觉得这个项目有一定的"诈骗"性质，诱导开发者以为你做了个很牛逼的东西，绕过了支付宝和微信的资质要求，结果就是个付款触发通知，付款的信息正确与否根本没法自动判断，可惜github没有举报通道。请你自动关闭这个项目，维护社区的干净，或者请你说明清楚，这个东西和你类比的那些软件完全是两个东西，这个玩意可以认为是聚合性的挂机通知系统罢了，需要人工验证，并不是自动回调验证，请你去掉你的不实信息。谢谢!

**Comment by code33** [comment]
顶上去

**Comment by Exrick** [comment]
Readme哪里没写清楚 官方通道自动回调 免签通道需要人工审核[微笑]
