### ISSUE TITLE
看了代码，原来是这样原理

### ISSUE THREAD

**Issue by skyisboss** [Exrick/xpay#8]
用户付款前【填写一个邮箱】然后扫码付款，然后开发者手动确认到账，注意了是【手动确认】，就是别人转账给你的微信提醒，然后你去web后台从数据库查看这个邮箱跟扫码付款的备注信息是否一致，然后确认到账。
哈哈，神奇的脑回路，我想说这个项目是来搞笑的吗，这样跟脱裤子放屁有啥区别

**Comment by Exrick** [comment]
这项目没有web后台 整个审核流程手机上进行 原理readme和官网都写有 不做自动监听原因也写有 支付测试可以填体验管理员邮箱
